#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../incomplete-test-harness-check ../incomplete-test-harness ../incomplete-test-harness-toplevel incomplete-test-harness-funcs ; else ./runt $@ ../incomplete-test-harness-check ../incomplete-test-harness ../incomplete-test-harness-toplevel incomplete-test-harness-funcs ; fi
cd - 2>&1 >/dev/null
