#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../solution-stub-code-check ../solution-stub-code ../solution-stub-code-toplevel solution-stub-code-funcs ; else ./runt $@ ../solution-stub-code-check ../solution-stub-code ../solution-stub-code-toplevel solution-stub-code-funcs ; fi
cd - 2>&1 >/dev/null
