#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../success-check ../success ../success-toplevel success-funcs ; else ./runt $@ ../success-check ../success ../success-toplevel success-funcs ; fi
cd - 2>&1 >/dev/null
