#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../all-fail-check ../all-fail ../all-fail-toplevel all-fail-funcs ; else ./runt $@ ../all-fail-check ../all-fail ../all-fail-toplevel all-fail-funcs ; fi
cd - 2>&1 >/dev/null
