#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../solution-no-code-check ../solution-no-code ../solution-no-code-toplevel solution-no-code-funcs ; else ./runt $@ ../solution-no-code-check ../solution-no-code ../solution-no-code-toplevel solution-no-code-funcs ; fi
cd - 2>&1 >/dev/null
