#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../syntax-check ../syntax ../syntax-toplevel syntax-funcs ; else ./runt $@ ../syntax-check ../syntax ../syntax-toplevel syntax-funcs ; fi
cd - 2>&1 >/dev/null
