#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../some-fail-check ../some-fail ../some-fail-toplevel some-fail-funcs ; else ./runt $@ ../some-fail-check ../some-fail ../some-fail-toplevel some-fail-funcs ; fi
cd - 2>&1 >/dev/null
